mode: tracks

# CoTracker tracking parameters
n_tracks: 400
init_queries: uniform
reinit: true
horizon: 16
batch_size: 8
precision: fp32          # fp32 | bf16 | fp16 | amp_auto
auto_batch: true         # OOM 时自动将批量减半重试
min_batch_size: 1

# Source / destination (Breakfast split1 webcam02, target_fps=10)
source: /home/johnny/action_ws/online_datasets/breakfast/breakfast/Videos_train.split1_webcam02
# 输出路径：以 m10 标注 target_fps=10，直接写入根目录（不额外加 split1 子目录）
output_dir: /home/johnny/action_ws/data/preprocessed_breakfast_webcam02_m10
dest: preprocessed_data
dataset_name: breakfast
skip_exist: true
recursive: false

# Video preprocessing
video_exts: [".avi"]
target_fps: 10
resize_shorter: 320
view_name: default
max_files: null
opencv_num_threads: 2

# Debug
verbose: true
video_progress_desc: "BreakfastSplit1Webcam02_m10"

# Parallelization
parallel:
  enable_io_prefetch: true   # overlap video decoding (IO) with GPU tracking compute
  io_workers: 8              # number of IO threads to decode frames
  prefetch_buffer: 2         # max pending decoded samples buffered in memory
  enable_multi_gpu: false    # enable DataParallel over available GPUs
  multi_gpu_device_ids: [0]
  enable_multiprocess_gpu: false
  mp_device_ids: [0]

